### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by esalman** [NDAR/AWS-Download#1]
https://github.com/NDAR/AWS-Download/blob/8b4195c349e7837f2308b6356658d30e2fe06982/awsdownload.py#L146

Hi, I think it will be a good idea to put a limit on the maximum number of workers here, like 8-10. I was running this code on a 80+ core machine and it resulted in `OSError: too many open files`.

**Comment by ushnaahmad** [comment]
> [AWS-Download/awsdownload.py](https://github.com/NDAR/AWS-Download/blob/8b4195c349e7837f2308b6356658d30e2fe06982/awsdownload.py#L146)
> 
> Line 146 in [8b4195c](/NDAR/AWS-Download/commit/8b4195c349e7837f2308b6356658d30e2fe06982)
> 
>  for x in range(cpu_num): 
> Hi, I think it will be a good idea to put a limit on the maximum number of workers here, like 8-10. I was running this code on a 80+ core machine and it resulted in `OSError: too many open files`.

@esalman 
Hi, thank you for reporting this issue. I just wanted to let you know the script has been updated since then and while it still uses the same number of workers as cpu on your machine, it will make sure to terminate the threads cleanly. Previously, new threads were being spawned instead of using a set amount. Let us know if you continue having problems.

**Comment by DVSneuro** [comment]
Hi, we're running into the same (or maybe a similar?) problem with the updated code:

    SSL validation failed for https://s3.amazonaws.com/NDAR_Central_1/submission_16888/NDARINV60VLVXBP_baselineYear1Arm1_ABCD-MPROC-MID-fMRI_20170122180408.tgz [Errno 24] Too many open files
    SSL validation failed for https://s3.amazonaws.com/NDAR_Central_1/submission_16888/NDARINVRE48TR17_baselineYear1Arm1_ABCD-MPROC-MID-fMRI_20170711151229.tgz [Errno 24] Too many open files
    [Errno 24] Too many open files: '/home/ubuntu/.local/lib/python2.7/site-packages/botocore/data/application-autoscaling'
    [Errno 24] Too many open files: '/home/ubuntu/.local/lib/python2.7/site-packages/botocore/data/endpoints.json'
    [Errno 24] Too many open files: '/home/ubuntu/.local/lib/python2.7/site-packages/botocore/data/mobile'
    Could not connect to the endpoint URL: "https://s3.amazonaws.com/NDAR_Central_1/submission_16888/NDARINVKV552N4Y_baselineYear1Arm1_ABCD-MPROC-MID-fMRI_20161206171025.tgz"

We're running this on a machine with 96 CPUs, and we're trying to grab the data from about 150 ABCD subjects (two tasks). Any ideas?

Also, since we're bumping into this issue a lot with large downloads, are we correct in thinking that adding the `--resume` flag to our command will at least let the download script pick up where it left off for these failed/incomplete downloads? 

`python awsdownload.py -t s3links_n150_T1_MID_FMaps_SST.txt -d /data/projects/abcd-mid/raw/fasttrack --resume`

Thanks for any help!

**Comment by ushnaahmad** [comment]
Hi @DVSneuro ,

It looks like you are running into the same issue. The code was updated not to spawn additional worker threads, but it still uses the number of CPU - 1 as a default to set that number initially. In your case, it looks like it would set it to 95, and therefore, give you the error. 

I would recommend you use our Python package, nda-tools](https://pypi.org/project/nda-tools/), to download your data. It has a built-in command line tool, downloadcmd, that has the same options as this script, but is more regularly updated. This tool has an additional flag to set the number of worker threads, so I suggest you change it something smaller and more manageable, ex. -wt 12.

Lastly, the --resume flag will resume the download of the package, not the actual file. That is, if a file has been successfully downloaded and can be located at the directory specified, then it will skip downloading that file again. If the file previously began downloading but was interrupted, it will resume the download from the beginning. I agree it would be useful to have files pick up downloading from where they left off, and this is something we are adding to our validation tool uploads for the next release. I suggest if this is something you like, please go ahead and make a feature request for nda-tools.

**Comment by DVSneuro** [comment]
Thanks! We'll give that a try when we start downloading more data.
